---
- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - mysql
    - rabbitmq-server
    - keystone
    - glance
    - nova-controller
    - neutron-controller
    - neutron-network
    - nova-compute
