---
- name: ensure that dashboard is configured to log in to keystone
  lineinfile:
    dest: /etc/openstack-dashboard/local_settings.py
    line: OPENSTACK_HOST = "{{ openstack_identity_endpoint_host }}"
    regexp: ^OPENSTACK_HOST\s*=
    state: present
  register: modify_local_settings

# Trying to fix restart problem...
- name: stop openstack dashboard if necessary
  service:
    name: "{{ item}}"
    state: stopped
  with_items:
    - apache2
    - memcached
  when: modify_local_settings|changed

- name: restart openstack dashboard if necessary
  service:
    name: "{{ item}}"
    state: restarted
  with_items:
    - apache2
    - memcached
  when: modify_local_settings|changed
