---
- name: ensure openstack horizon requirements packages are installed
  action: "{{ openstack_horizon_package_info.pkg_mgr }}"
  args: openstack_horizon_package_info.args
  with_items: openstack_horizon_package_info.pre_pkgs
  when: openstack_horizon_package_info.pre_pkgs|length > 0

- name: ensure openstack repository is enabled
  action: "{{ openstack_horizon_repo_info.pkg_repo }}"
  args: openstack_horizon_repo_info.args
  with_items: openstack_horizon_repo_info.repos
  when: openstack_horizon_repo_info.repos|length > 0

- name: ensure openstack horizon packages are installed
  action: "{{ openstack_horizon_package_info.pkg_mgr }}"
  args: openstack_horizon_package_info.args
  with_items: openstack_horizon_package_info.pkgs
  when: openstack_horizon_package_info.pkgs|length > 0

- name: ensure undesirable openstack horizon packages are purged
  action: "{{ openstack_horizon_package_info.pkg_mgr }}"
  args: openstack_horizon_package_info.purge_args
  with_items: openstack_horizon_package_info.purge_pkgs
  when: openstack_horizon_package_info.purge_pkgs|length > 0

- name: ensure horizon services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: openstack_horizon_services
  when: openstack_horizon_services|length > 0
