---
- name: ensure that software-properties-common is installed if needed
  apt: 
    pkg: software-properties-common
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  when: ansible_distribution_release == "precise"

- name: ensure that ubuntu cloud archive is available if needed
  command: apt-add-repository cloud-archive:icehouse
  when: ansible_distribution_release == "precise"
  
- name: ensure horizon packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - memcached
    - openstack-dashboard

- name: ensure ubuntu theme is purged
  apt: 
    pkg: "{{ item }}"
    state: purged
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - openstack-dashboard-ubuntu-theme

- name: ensure web server is started and enabled
  service: 
    name: apache2
    state: started 
    enabled: yes
